//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace monamedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int customerID { get; set; }
        public int accountID { get; set; }
        public string fullName { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public Nullable<bool> gender { get; set; }
        public string address { get; set; }
        public string phoneNumber { get; set; }
        public string accountStatus { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
