//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace monamedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Export
    {
        public int exportID { get; set; }
        public Nullable<int> staffID { get; set; }
        public Nullable<int> managerID { get; set; }
        public Nullable<int> orderID { get; set; }
        public Nullable<System.DateTime> pickUpTime { get; set; }
        public string status { get; set; }
    
        public virtual C_Order C_Order { get; set; }
        public virtual C_Order C_Order1 { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Manager Manager1 { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
    }
}
