//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace monamedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderDetail
    {
        public int orderDetailID { get; set; }
        public Nullable<int> orderID { get; set; }
        public string productID { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual C_Order C_Order { get; set; }
        public virtual C_Order C_Order1 { get; set; }
        public virtual Product Product { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
